import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavBar from "@/components/NavBar";
import { Separator } from "@/components/ui/separator";
import AlertPopUp from "@/components/reusable/Toaster/AlertPopUp";
import Providers from "./providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <AlertPopUp />
        <Providers>
          <SidebarProvider>
            <SideNav />
            <main className="w-full">
              <div className="w-full px-2">
                <NavBar />
                <Separator />
                {children}
              </div>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
