const SERVER_CONSTANTS = {
  FOLDER_PATH: "C:/NextJS/data",
  CUSTOMER_FILE_PATH: "C:/NextJS/data/master/customers",
  PRODUCTS_FILE_PATH: "C:/NextJS/data/master/products",
  CUSTOMER_TIME_UPDATION: 1200000,
  PRODUCT_TIME_UPDATION: 1200000,
  EXCEL_SHEET_NAMES: {
    INDENT: "INDENT",
  },
  PRODUCT_ORDER_CONFIG: ["MILK", "CURD", "PANEER", "GHEE", "BADAM", "DRINKS"],
};
export default SERVER_CONSTANTS;
