const SERVER_CONSTANTS = {
  FOLDER_PATH: "C:/NextJS/data",
  CUSTOMER_FILE_PATH: "C:/NextJS/data/master/customers",
  PRODUCTS_FILE_PATH: "C:/NextJS/data/master/products",
  CUSTOMER_TIME_UPDATION: 12000000,
  PRODUCT_TIME_UPDATION: 12000000,
  EXCEL_SHEET_NAMES: {
    INDENT: "INDENT",
  },
};
export default SERVER_CONSTANTS;
