const indentLedger = {
  success: true,
  message: "Data fetched successfully",
  error_code: "",
  errors: [],
  data: {
    transactions: [
      {
        serial_number: "INV-3",
        document_date: "28-11-2025",
        customer: {
          id: "5",
          name: "Kattunga Srinu",
          country_code: "91",
          phone_number: "",
          company_name: "",
          email: "",
          gstin: "",
        },
        due_date: "28-11-2025",
        amount_paid: 0.0,
        amount_pending: 3200.0,
        reference: "",
        notes: "",
        terms: "",
        is_created_by_recurring: 0,
        net_amount: 3200.0,
        hash_id: "SLwma4eSNNlP1",
        payment_status: "pending",
        payments: [],
        tax_amount: 0.0,
        total_amount: 3200.0,
        total_discount: 0.0,
      },
      //   {
      //     serial_number: "INV-2",
      //     document_date: "27-11-2025",
      //     customer: {
      //       id: "5",
      //       name: "Kattunga Srinu",
      //       country_code: "91",
      //       phone_number: "",
      //       company_name: "",
      //       email: "",
      //       gstin: "",
      //     },
      //     due_date: "27-11-2025",
      //     amount_paid: 0.0,
      //     amount_pending: 6150.0,
      //     reference: "",
      //     notes: "",
      //     terms: "",
      //     is_created_by_recurring: 0,
      //     net_amount: 6150.0,
      //     hash_id: "SLWbjJLIPP7rG",
      //     payment_status: "pending",
      //     payments: [],
      //     tax_amount: 0.0,
      //     total_amount: 6150.0,
      //     total_discount: 0.0,
      //   },
      //   {
      //     serial_number: "INV-1",
      //     document_date: "27-11-2025",
      //     customer: {
      //       id: "5",
      //       name: "Kattunga Srinu",
      //       country_code: "91",
      //       phone_number: "",
      //       company_name: "",
      //       email: "",
      //       gstin: "",
      //     },
      //     due_date: "27-11-2025",
      //     amount_paid: 0.0,
      //     amount_pending: 5360.0,
      //     reference: "",
      //     notes: "",
      //     terms: "",
      //     is_created_by_recurring: 0,
      //     net_amount: 5360.0,
      //     hash_id: "SLnx5rehppQ34",
      //     payment_status: "pending",
      //     payments: [],
      //     tax_amount: 0.0,
      //     total_amount: 5360.0,
      //     total_discount: 0.0,
      //   },
    ],
    total_records: 3,
  },
  request_id: "9cc41916-0569-4305-8c68-7cacd63bb5d7",
  timestamp: "2025-12-29 16:08:01.474930",
};
export default indentLedger;
